### ISSUE TITLE
position of entry type link

### ISSUE THREAD

**Issue by dralshehri** [mmikkel/CpFieldLinks-Craft#1]
I found that the "Edit Entry Type" link is pushing the live preview link away. Perhaps we need to decrease it's top margin.

![entry-type-link-bug](https://cloud.githubusercontent.com/assets/542855/12070339/02e2676a-b07f-11e5-9078-9c78e8ea7b6f.png)

**Comment by mmikkel** [comment]
Thanks for reporting! I'll get that sorted ASAP.

**Comment by mmikkel** [comment]
This is fixed in v. 1.0.1. I had to move the cogwheel to the settings sidebar (i.e. below the slug settings etc), because it got too difficult to render it in that position without breaking the CP layout. I feel it's an appropriate position, though, if not a little bit harder to spot.

Again, thanks for reporting!
